using System;
using System.Collections.Generic;

using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;

using ZScript.CodeGeneration.Messages;
using ZScript.CodeGeneration.Tokenizers;
using ZScript.Elements;
using ZScript.Runtime;

namespace ZScript.CodeGeneration
{
    /// <summary>
    /// Helper entry point for the ZScript library
    /// </summary>
    public class ZRuntimeGenerator
    {
        /// <summary>
        /// The input string to parse
        /// </summary>
        private string _input;

        /// <summary>
        /// The error listener for the parsing of the script
        /// </summary>
        private ZScriptErrorListener _errorListener;

        /// <summary>
        /// The parse tree that was generated by the parser
        /// </summary>
        private IParseTree _tree;

        /// <summary>
        /// The parser for the currently parsed script
        /// </summary>
        private ZScriptParser _parser;

        /// <summary>
        /// Gets or sets the script string input
        /// </summary>
        public string Input
        {
            get { return _input; }
            set { _input = value; }
        }

        /// <summary>
        /// Returns the array of all the syntax errors that were found during the parsing of the script
        /// </summary>
        public SyntaxError[] SyntaxErrors
        {
            get { return _errorListener.SyntaxErrors.ToArray(); }
        }

        /// <summary>
        /// Gets a value specifying whether there were any syntax errors on the script generation process
        /// </summary>
        public bool HasSyntaxErrors
        {
            get { return _errorListener != null && _errorListener.SyntaxErrors.Count > 0; }
        }

        /// <summary>
        /// Creates a new instance of the ZScriptGenerator class using a specified string as input
        /// </summary>
        /// <param name="input">The input string containing the code to parse</param>
        public ZRuntimeGenerator(string input)
        {
            _input = input;
        }

        /// <summary>
        /// Parses the input string
        /// </summary>
        public void ParseInputString()
        {
            _errorListener = new ZScriptErrorListener();

            AntlrInputStream stream = new AntlrInputStream(_input);
            ITokenSource lexer = new ZScriptLexer(stream);
            ITokenStream tokens = new CommonTokenStream(lexer);
            
            _parser = new ZScriptParser(tokens)
            {
                BuildParseTree = true,
                //Interpreter = {PredictionMode = PredictionMode.Sll}
            };

            // Reset error listener
            _errorListener.SyntaxErrors.Clear();
            _parser.AddErrorListener(_errorListener);

            try
            {
                _tree = _parser.program();
            }
            // Deal with parse exceptions
            catch (ParseCanceledException)
            {
                _parser.Interpreter.PredictionMode = PredictionMode.Ll;
                
                // Reset error listener
                _errorListener.SyntaxErrors.Clear();

                _tree = _parser.program();
            }
        }

        /// <summary>
        /// Generates a new runtime definition based on the script that was parsed
        /// </summary>
        /// <returns>A newly created ZRuntimeDefinition object that can be used to execute the parsed code</returns>
        public ZRuntimeDefinition GenerateRuntimeDefinition()
        {
            var runtimeDefinition = new ZRuntimeDefinition();

            var walker = new ParseTreeWalker();
            var functionListener = new FunctionDefinitionListener(runtimeDefinition);

            walker.Walk(functionListener, _tree);

            return runtimeDefinition;
        }

        /// <summary>
        /// Generates a new runtime based on the script that was parsed, setting the provided runtime owner as the owner of the runtime object to create
        /// </summary>
        /// <param name="owner">A runtime owner object that will own the runtime to be created</param>
        /// <returns>A newly created ZRuntime object that can be used to execute the parsed code</returns>
        public ZRuntime GenerateRuntime(IRuntimeOwner owner)
        {
            return new ZRuntime(GenerateRuntimeDefinition(), owner);
        }

        /// <summary>
        /// Error listener for the parsing
        /// </summary>
        private class ZScriptErrorListener : BaseErrorListener
        {
            /// <summary>
            /// A list of all the syntax errors reported
            /// </summary>
            public readonly List<SyntaxError> SyntaxErrors = new List<SyntaxError>();

            // 
            // SintaxError listener
            // 
            public override void SyntaxError(IRecognizer recognizer, IToken offendingSymbol, int line, int charPositionInLine, string msg, RecognitionException e)
            {
                SyntaxErrors.Add(new SyntaxError(line, charPositionInLine, msg));
            }
        }

        /// <summary>
        /// Base class for runtime-generation node listeners
        /// </summary>
        private abstract class ZScriptNodeListener : ZScriptBaseListener
        {
            /// <summary>
            /// The runtime definition to populate with this listener
            /// </summary>
            protected readonly ZRuntimeDefinition RuntimeDefinition;

            /// <summary>
            /// Initializes a new instance of the ZScriptNodeListener class
            /// </summary>
            /// <param name="runtimeDefinition">The runtime to generate code to</param>
            protected ZScriptNodeListener(ZRuntimeDefinition runtimeDefinition)
            {
                RuntimeDefinition = runtimeDefinition;
            }
        }

        /// <summary>
        /// Listener that binds functions to the global scope 
        /// </summary>
        private class FunctionDefinitionListener : ZScriptNodeListener
        {
            /// <summary>
            /// Initializes a new FunctionNodeListener class instance
            /// </summary>
            /// <param name="runtimeDefinition">The runtime to generate code for</param>
            public FunctionDefinitionListener(ZRuntimeDefinition runtimeDefinition) : base(runtimeDefinition) { }

            // EnterFunctionDefinition override
            public override void EnterFunctionDefinition(ZScriptParser.FunctionDefinitionContext context)
            {
                base.EnterFunctionDefinition(context);

                RuntimeDefinition.AddFunctionDef(GenerateFunctionDef(context));
            }

            /// <summary>
            /// Generates a new function definition using the given context
            /// </summary>
            /// <param name="context">The context to generate the function definition from</param>
            /// <returns>A function definition generated from the given context</returns>
            private FunctionDef GenerateFunctionDef(ZScriptParser.FunctionDefinitionContext context)
            {
                var tokenizer = new FunctionBodyTokenizer();
                var definition = new FunctionDef(context.functionName().IDENT().GetText())
                {
                    Tokens = tokenizer.TokenizeBody(context.functionBody())
                };

                return definition;
            }
        }
    }
}